### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by tux7k** [envyjs/charon#1]
Hello!

I'm submitting an issue because I believe there is an issue with the license of this project, technically being a derivative work of Pluto. Since we cannot confirm that you (or the org), have read any of the original work, and re-written it, we (the Zeon team) request that the license is changed to GPL-v3 to be compatible ASAP.

Thanks,
tux7k.

**Comment by OwnedByWuigi** [comment]
It is not a deriative work, but rather a reverse-engineering project.

ReactOS is not a deriative of Windows, so is Charon not a deriative of Pluto.

Closed.
